config/routes.rb
CrownAsia::Application.routes.draw do
  resources :delivery_schedules do
    get 'cancel', :on => :member
    post 'cancel_schedule', :on => :member
    post 'update_item_selection', :on => :collection
  end

  resources :personnels

  resources :positions

  resources :trucks

  resources :generated_certificate_of_qualities do
    get 'search', :on => :collection
    post 'search', :on => :collection
  end

  resources :certificate_of_qualities do
    get 'search', :on => :collection
    post 'search', :on => :collection
  end

  resources :coq_properties

  resources :sales_quotes

  resources :costing_periods

  resources :issued_formula_batches do
    get 'process_batch', :on => :member
    get 'unprocess_batch', :on => :member
  end
  
  resources :issued_formulas do
    post 'update_finished_good', :on => :collection
    post 'update_formula', :on => :collection
    post 'update_item_list', :on => :collection
    post 'show_formula_comment', :on => :collection
    get 'cancel_big_batch', :on => :member
    get 'cancel_small_batch', :on => :member
  end

  resources :formulas do
    post 'update_finished_good', :on => :collection
    post 'update_raw_materials', :on => :collection
  end

  resources :extruders

  resources :mixers

  resources :bags do
    get 'return', :on => :collection
    post 'return', :on => :collection
    post 'update_lot_numbers', :on => :collection
  end
  
  resources :accounts
  
  resources :roles

  resources :finished_good_transactions do
    post 'update_sender', :on => :collection
    post 'update_bags', :on => :collection
    post 'update_issued', :on => :collection
    post 'update_underpack', :on => :collection
  end

  resources :finished_goods do
    get 'transactions', :on => :member
    post 'populate_fields_from_delivery_schedule_items', :on => :member
  end

  resources :supply_transactions do
    post 'update_supplies', :on => :collection
  end

  resources :supplies do
    get 'transactions', :on => :member
  end

  resources :raw_material_transactions do
    post 'update_sender', :on => :collection
    post 'update_issued', :on => :collection
  end

  resources :raw_materials do
    get 'transactions', :on => :member
  end

  resources :raw_material_types

  resources :departments

  resources :unit_of_measures

  resources :customers

  resources :suppliers

  devise_for :users, :path_prefix => 'd'
  
  resources :users
  
  match 'permissions' => 'permissions#index'
  

  root :to => 'home#index'

end

app/models/position.rb
class Position < ActiveRecord::Base
  validates :name, :presence => true
  
  has_many :personnels
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_filter :authorize_view, :only => [:index]
  before_filter(:only => [:index]) { |c| c.clear_search_session([:position_name]) }
  before_filter :authorize_create, :only => [:new, :create]
  before_filter :authorize_update, :only => [:edit, :update]
  before_filter :authorize_delete, :only => [:destroy]
  
  def index
    session[:search][:position_name] = params[:position_name] if !params[:position_name].nil?
    
    @positions = Position.paginate(:per_page => 20, :page => params[:page])
    @positions = @positions.where("name LIKE ?", "%#{session[:search][:position_name]}%") unless session[:search][:position_name].blank?
    @positions = @positions.order("name")
  end
  
  def new
    @position = Position.new
  end
  
  def create
    @position = Position.new(params[:position])
    if @position.save
      flash[:notice] = "Position saved successfully"
      redirect_to positions_path
    else
      render :action => "new"
    end
  end
  
  def edit
    @position = Position.find(params[:id])
  end
  
  def update
    @position = Position.find(params[:id])
    if @position.update_attributes(params[:position])
      flash[:notice] = "#{@position.name} was updated successfully"
      redirect_to positions_path
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @position = Position.find(params[:id])
    @position.destroy
    flash[:notice] = "#{@position.name} was deleted successfully"
    redirect_to positions_path
  end
  
  protected
  
    def authorize_view
      authorize! :view, Position
    end
    
    def authorize_create
      authorize! :create, Position
    end
    
    def authorize_update
      authorize! :update, Position
    end
    
    def authorize_delete
      authorize! :delete, Position
    end
  
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<fieldset>
  <dl>
    <dd><%= f.label :name %></dd>
    <dd><%= f.text_field :name %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :active %></dd>
    <dd><%= f.check_box :active %></dd>
  </dl>
</fieldset>

app/views/positions/edit.html.erb
<h1>Update <%= @position.name %></h1>

<%= render :partial => "shared/error_messages", :locals => {:target => @position} %>

<%= form_for @position do |f| %>
  <%= render :partial => "form", :locals =>{:f => f} %>
  
  <p class="buttons">
    <%= submit_tag "Save" %>
    <%= button_to_function "Reset", "$(this).closest('form')[0].reset()" %>
    <%= button_to_function "Cancel", "window.location.replace('#{positions_path}')" %>
  </p>
<% end %>

app/views/positions/index.html.erb
<h1>Positions</h1>

<%= form_tag "", :method => :get, :id => "search_form" do %>
  <label>Position: </label><%= text_field_tag "position_name", session[:search][:position_name] %> 
  <%= link_to_function "Search", "$('#search_form').submit()", :class => "search_link" %>
<% end %>

<%= link_to "Add Position", new_position_path, :class => "create_link" if can?(:create, Position) %>

<br class="clear"/><br/>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
  <% @positions.each do |position| %>
    <tr class="<%= cycle("light", "dark") %>">
      <td><%= position.name %></td>
      <td><%= position.active ? "Yes" : "No" %></td>
      <td>
        <%= link_to "Edit", edit_position_path(position), :class => "edit_link" if can?(:update, Position) %> &nbsp;&nbsp;
        <%= link_to "Delete", position_path(position), :class => "delete_link", :method => :delete, :confirm => "Are you sure?" if can?(:delete, Position) %> <br/>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @positions %>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render :partial => "shared/error_messages", :locals => {:target => @position} %>

<%= form_for @position do |f| %>
  <%= render :partial => "form", :locals =>{:f => f} %>
  
  <p class="buttons">
    <%= submit_tag "Save" %>
    <%= button_to_function "Reset", "$('#new_position')[0].reset()" %>
    <%= button_to_function "Cancel", "window.location.replace('#{positions_path}')" %>
  </p>
<% end %>