config/routes.rb
CrownAsia::Application.routes.draw do
  resources :delivery_schedules do
    get 'cancel', :on => :member
    post 'cancel_schedule', :on => :member
    post 'update_item_selection', :on => :collection
  end

  resources :personnels

  resources :positions

  resources :trucks

  resources :generated_certificate_of_qualities do
    get 'search', :on => :collection
    post 'search', :on => :collection
  end

  resources :certificate_of_qualities do
    get 'search', :on => :collection
    post 'search', :on => :collection
  end

  resources :coq_properties

  resources :sales_quotes

  resources :costing_periods

  resources :issued_formula_batches do
    get 'process_batch', :on => :member
    get 'unprocess_batch', :on => :member
  end
  
  resources :issued_formulas do
    post 'update_finished_good', :on => :collection
    post 'update_formula', :on => :collection
    post 'update_item_list', :on => :collection
    post 'show_formula_comment', :on => :collection
    get 'cancel_big_batch', :on => :member
    get 'cancel_small_batch', :on => :member
  end

  resources :formulas do
    post 'update_finished_good', :on => :collection
    post 'update_raw_materials', :on => :collection
  end

  resources :extruders

  resources :mixers

  resources :bags do
    get 'return', :on => :collection
    post 'return', :on => :collection
    post 'update_lot_numbers', :on => :collection
  end
  
  resources :accounts
  
  resources :roles

  resources :finished_good_transactions do
    post 'update_sender', :on => :collection
    post 'update_bags', :on => :collection
    post 'update_issued', :on => :collection
    post 'update_underpack', :on => :collection
  end

  resources :finished_goods do
    get 'transactions', :on => :member
    post 'populate_fields_from_delivery_schedule_items', :on => :member
  end

  resources :supply_transactions do
    post 'update_supplies', :on => :collection
  end

  resources :supplies do
    get 'transactions', :on => :member
  end

  resources :raw_material_transactions do
    post 'update_sender', :on => :collection
    post 'update_issued', :on => :collection
  end

  resources :raw_materials do
    get 'transactions', :on => :member
  end

  resources :raw_material_types

  resources :departments

  resources :unit_of_measures

  resources :customers

  resources :suppliers

  devise_for :users, :path_prefix => 'd'
  
  resources :users
  
  match 'permissions' => 'permissions#index'
  

  root :to => 'home#index'

end

app/models/supply.rb
class Supply < ActiveRecord::Base

  belongs_to :unit_of_measure
  belongs_to :creator, :class_name => "User"
  belongs_to :updater, :class_name => "User"
  
  has_many :supply_transaction_items, :dependent => :destroy
  
  has_many :delivery_schedule_items, :as => :item
  
  validates :name, :unit_of_measure, :supply_type, :presence => true
  
  acts_as_paranoid
  
  acts_as_audited :except => [:deleted_at]
  
  scope :active, :conditions => {:active => true}, :order => "name"
  
  def quantity_on_hand
    add_quantity = SupplyTransactionItem.sum("quantity", :include => [:supply_transaction], :conditions => ["supply_transactions.transaction_type = 'add' AND supply_transaction_items.supply_id = ?", self.id])
    sub_quantity = SupplyTransactionItem.sum("quantity", :include => [:supply_transaction], :conditions => ["supply_transactions.transaction_type = 'sub' AND supply_transaction_items.supply_id = ?", self.id])
    
    add_quantity - sub_quantity
  end
  
  def last_transaction_date
    s = self.supply_transaction_items.first(:include => [:supply_transaction], :order => "supply_transactions.transaction_date DESC")
    return nil if s.nil?
    return s.supply_transaction.transaction_date
  end
  
  def last_price
    s = self.supply_transaction_items.first(:include => [:supply_transaction], :conditions => ["supply_transactions.transaction_type = 'add'"], :order => "supply_transactions.transaction_date DESC")
    return nil if s.nil?
    return s.unit_price
  end
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_filter :authorize_view, :only => [:index]
  before_filter(:only => [:index]) { |c| c.clear_search_session([:supply_name, :supply_type]) }
  before_filter :authorize_create, :only => [:new, :create]
  before_filter :authorize_update, :only => [:edit, :update]
  before_filter :authorize_delete, :only => [:destroy]
  before_filter :authorize_transactions, :only => [:transactions]
  
  def index
    session[:search][:supply_name] = params[:search_text] if !params[:search_text].nil?
    session[:search][:supply_type] = params[:type_text] if !params[:type_text].nil?
    
    @supplies = Supply.paginate(:per_page => 20, :page => params[:page])
    @supplies = @supplies.where("name LIKE ? AND supply_type LIKE ?", "%#{session[:search][:supply_name]}%", "%#{session[:search][:supply_type]}%")
    @supplies = @supplies.order("name")
  end
  
  def new
    @supply = Supply.new
  end
  
  def create
    @supply = Supply.new(params[:supply])
    @supply.creator = current_user
    if @supply.save
      flash[:notice] = "Supply saved successfully"
      redirect_to supplies_path
    else
      render :action => "new"
    end
  end
  
  def edit
    @supply = Supply.find(params[:id])
  end
  
  def update
    @supply = Supply.find(params[:id])
    @supply.updater = current_user
    if @supply.update_attributes(params[:supply])
      flash[:notice] = "#{@supply.name} was updated successfully"
      redirect_to supplies_path
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @supply = Supply.find(params[:id])
    @supply.destroy
    flash[:notice] = "#{@supply.name} was deleted successfully"
    redirect_to supplies_path
  end
  
  def transactions
    @supply = Supply.find(params[:id])
    @transactions = @supply.supply_transaction_items.paginate(:per_page => 20, :page => params[:page], :include => [:supply_transaction], :order => "supply_transactions.transaction_date DESC")
  end
  
  protected
  
    def authorize_view
      authorize! :view, Supply
    end
    
    def authorize_create
      authorize! :create, Supply
    end
    
    def authorize_update
      authorize! :update, Supply
    end
    
    def authorize_delete
      authorize! :delete, Supply
    end
    
    def authorize_transactions
      authorize! :transactions, Supply
    end
    
end

app/helpers/supplies_helper.rb
module SuppliesHelper

  def supply_type_options
    [["O/C", "O/C"],
     ["Packaging", "Packaging"],
     ["Engineering", "Engineering"],
     ["Scrap", "Scrap"]]
  end

end

app/views/supplies/_form.html.erb
<fieldset>
  <dl>
    <dd><%= f.label :supply_type %></dd>
    <dd><%= f.select :supply_type, supply_type_options, {:include_blank => true} %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :name %></dd>
    <dd><%= f.text_field :name %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :description %></dd>
    <dd><%= f.text_area :description %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :active %></dd>
    <dd><%= f.check_box :active %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :compounds %></dd>
    <dd><%= f.check_box :compounds %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :pipes %></dd>
    <dd><%= f.check_box :pipes %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :corporate %></dd>
    <dd><%= f.check_box :corporate %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :unit_of_measure %></dd>
    <dd><%= f.select :unit_of_measure_id, UnitOfMeasure.all(:order => "code").collect{|u| [u.name, u.id]}, {:include_blank => true} %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :comments %></dd>
    <dd><%= f.text_area :comments %></dd>
  </dl>
</fieldset>

app/views/supplies/edit.html.erb
<h1>Update <%= @supply.name %></h1>

<%= render :partial => "shared/error_messages", :locals => {:target => @supply} %>

<%= form_for @supply do |f| %>
  <%= render :partial => "form", :locals =>{:f => f} %>
  
  <p class="buttons">
    <%= submit_tag "Save" %>
    <%= button_to_function "Reset", "$(this).closest('form')[0].reset()" %>
    <%= button_to_function "Cancel", "window.location.replace('#{supplies_path}')" %>
  </p>
<% end %>

app/views/supplies/index.html.erb
<h1>Supplies</h1>

<%= form_tag "", :method => :get, :id => "search_form" do %>
  <%= text_field_tag "search_text", session[:search][:supply_name] %> 
  <%= select_tag "type_text", options_for_select([""] + supply_type_options, session[:search][:supply_type]) %>
  <%= link_to_function "Search", "$('#search_form').submit()", :class => "search_link" %>
<% end %>

<%= link_to "Add Supply", new_supply_path, :class => "create_link" if can?(:create, Supply) %>
<%= link_to "Add", new_supply_transaction_path(:transaction_type => "add"), :class => "create_link" if can?(:create, SupplyTransaction) %>
<%= link_to "Deduct", new_supply_transaction_path(:transaction_type => "sub"), :class => "delete_link" if can?(:create, SupplyTransaction) %>

<br class="clear"/><br/>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Active?</th>
      <th>Compounds</th>
      <th>Pipes</th>
      <th>Corporate</th>
      <th>UOM</th>
      <th>Quantity</th>
      <th>Last Transaction</th>
      <th>Comments</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
  <% @supplies.each do |supply| %>
    <tr class="<%= cycle("light", "dark") %>">
      <td><%= supply.supply_type %></td>
      <td><%= supply.name %></td>
      <td><%= supply.active ? "Yes" : "No" %></td>
      <td><%= supply.compounds ? "Yes" : "No" %></td>
      <td><%= supply.pipes ? "Yes" : "No" %></td>
      <td><%= supply.corporate ? "Yes" : "No" %></td>
      <td><%= supply.unit_of_measure.name %></td>
      <td><%= supply.quantity_on_hand %></td>
      <td><%= supply.last_transaction_date.strftime("%m/%d/%Y") if supply.last_transaction_date %></td>
      <td><%= simple_format(supply.comments) %></td>
      <td>
        <%= link_to "Edit", edit_supply_path(supply), :class => "edit_link" if can?(:update, Supply) %> &nbsp;&nbsp;
        <%= link_to "Delete", supply_path(supply), :class => "delete_link", :method => :delete, :confirm => "Are you sure?" if can?(:delete, Supply) %> <br/>
        <%= link_to "History", transactions_supply_path(supply), :class => "history_link" if can?(:transactions, Supply) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @supplies %>

app/views/supplies/new.html.erb
<h1>New Supply</h1>

<%= render :partial => "shared/error_messages", :locals => {:target => @supply} %>

<%= form_for @supply do |f| %>
  <%= render :partial => "form", :locals =>{:f => f} %>
  
  <p class="buttons">
    <%= submit_tag "Save" %>
    <%= button_to_function "Reset", "$('#new_supply')[0].reset()" %>
    <%= button_to_function "Cancel", "window.location.replace('#{supplies_path}')" %>
  </p>
<% end %>

app/views/supplies/transactions.html.erb
<h1>Transactions for <%= @supply.name %></h1>

<%= link_to "Back", supplies_path, :class => "back_link" %>

<br/><br/>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Date</th>
      <th>Quantity</th>
      <th>Unit Price</th>
      <th>Supplier</th>
      <th>Reference Type
      <th>Reference #</th>
      <th>PRE #</th>
      <th>MIRS #</th>
      <th>Issued To Department</th>
      <th>Issued To User</th>
      <th>Comments</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
  <% @transactions.each do |transaction| %>
    <tr class="<%= cycle("light", "dark") %>">
      <td>
        <% if transaction.supply_transaction.transaction_type == "add" %>
          <span class="positive">Add</span>
        <% else %>
          <span class="negative">Deduct</span>
        <% end %>
      </td>
      <td><%= transaction.supply_transaction.transaction_date.strftime("%m/%d/%Y") if transaction.supply_transaction.transaction_date %></td>
      <td><%= transaction.quantity %></td>
      <td><%= transaction.unit_price %></td>
      <td><%= transaction.supply_transaction.supplier_name %></td>
      <td><%= transaction.supply_transaction.reference_type %></td>
      <td><%= transaction.supply_transaction.rr_number %></td>
      <td><%= transaction.supply_transaction.pre_number %></td>
      <td><%= transaction.supply_transaction.mirs_number %></td>
      <td><%= transaction.supply_transaction.issued_department.name if transaction.supply_transaction.issued_department %></td>
      <td><%= transaction.supply_transaction.issued_user.name if transaction.supply_transaction.issued_user %></td>
      <td><%= simple_format(transaction.supply_transaction.comments) %></td>
      <td>
        <%= link_to "Edit", edit_supply_transaction_path(transaction.supply_transaction), :class => "edit_link" if can?(:update, SupplyTransaction) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @transactions %>