config/routes.rb
CrownAsia::Application.routes.draw do
  resources :delivery_schedules do
    get 'cancel', :on => :member
    post 'cancel_schedule', :on => :member
    post 'update_item_selection', :on => :collection
  end

  resources :personnels

  resources :positions

  resources :trucks

  resources :generated_certificate_of_qualities do
    get 'search', :on => :collection
    post 'search', :on => :collection
  end

  resources :certificate_of_qualities do
    get 'search', :on => :collection
    post 'search', :on => :collection
  end

  resources :coq_properties

  resources :sales_quotes

  resources :costing_periods

  resources :issued_formula_batches do
    get 'process_batch', :on => :member
    get 'unprocess_batch', :on => :member
  end
  
  resources :issued_formulas do
    post 'update_finished_good', :on => :collection
    post 'update_formula', :on => :collection
    post 'update_item_list', :on => :collection
    post 'show_formula_comment', :on => :collection
    get 'cancel_big_batch', :on => :member
    get 'cancel_small_batch', :on => :member
  end

  resources :formulas do
    post 'update_finished_good', :on => :collection
    post 'update_raw_materials', :on => :collection
  end

  resources :extruders

  resources :mixers

  resources :bags do
    get 'return', :on => :collection
    post 'return', :on => :collection
    post 'update_lot_numbers', :on => :collection
  end
  
  resources :accounts
  
  resources :roles

  resources :finished_good_transactions do
    post 'update_sender', :on => :collection
    post 'update_bags', :on => :collection
    post 'update_issued', :on => :collection
    post 'update_underpack', :on => :collection
  end

  resources :finished_goods do
    get 'transactions', :on => :member
    post 'populate_fields_from_delivery_schedule_items', :on => :member
  end

  resources :supply_transactions do
    post 'update_supplies', :on => :collection
  end

  resources :supplies do
    get 'transactions', :on => :member
  end

  resources :raw_material_transactions do
    post 'update_sender', :on => :collection
    post 'update_issued', :on => :collection
  end

  resources :raw_materials do
    get 'transactions', :on => :member
  end

  resources :raw_material_types

  resources :departments

  resources :unit_of_measures

  resources :customers

  resources :suppliers

  devise_for :users, :path_prefix => 'd'
  
  resources :users
  
  match 'permissions' => 'permissions#index'
  

  root :to => 'home#index'

end

app/models/mixer.rb
class Mixer < ActiveRecord::Base
  belongs_to :creator, :class_name => "User"
  belongs_to :updater, :class_name => "User"
  
  validates :name, :brand, :presence => true
  
  scope :active_mixers, :conditions => {:active => true}, :order => "name"
end

app/controllers/mixers_controller.rb
class MixersController < ApplicationController
  before_filter :authorize_view, :only => [:index]
  before_filter(:only => [:index]) { |c| c.clear_search_session([:mixer_search_text]) }
  before_filter :authorize_create, :only => [:new, :create]
  before_filter :authorize_update, :only => [:edit, :update]
  before_filter :authorize_delete, :only => [:destroy]
  
  def index
    session[:search][:mixer_search_text] = params[:search_text] if !params[:search_text].nil?
    @mixers = Mixer.paginate(:per_page => 20, :page => params[:page])
    @mixers = @mixers.where("name LIKE ?", "%#{session[:search][:mixer_search_text]}%")
    @mixers = @mixers.order("name")
  end
  
  def new
    @mixer = Mixer.new
  end
  
  def create
    @mixer = Mixer.new(params[:mixer])
    @mixer.creator = current_user
    if @mixer.save
      flash[:notice] = "Mixer saved successfully"
      redirect_to mixers_path
    else
      render :action => "new"
    end
  end
  
  def edit
    @mixer = Mixer.find(params[:id])
  end
  
  def update
    @mixer = Mixer.find(params[:id])
    @mixer.updater = current_user
    if @mixer.update_attributes(params[:mixer])
      flash[:notice] = "#{@mixer.name} was updated successfully"
      redirect_to mixers_path
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @mixer = Mixer.find(params[:id])
    @mixer.destroy
    flash[:notice] = "#{@mixer.name} was deleted successfully"
    redirect_to mixers_path
  end
  
  protected
  
    def authorize_view
      authorize! :view, Mixer
    end
    
    def authorize_create
      authorize! :create, Mixer
    end
    
    def authorize_update
      authorize! :update, Mixer
    end
    
    def authorize_delete
      authorize! :delete, Mixer
    end
end

app/helpers/mixers_helper.rb
module MixersHelper
end

app/views/mixers/_form.html.erb
<fieldset>
  <dl>
    <dd><%= f.label :name %></dd>
    <dd><%= f.text_field :name %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :brand %></dd>
    <dd><%= f.text_field :brand %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :active %></dd>
    <dd><%= f.check_box :active %></dd>
  </dl>
</fieldset>

app/views/mixers/edit.html.erb
<h1>Update <%= @mixer.name %></h1>

<%= render :partial => "shared/error_messages", :locals => {:target => @mixer} %>

<%= form_for @mixer do |f| %>
  <%= render :partial => "form", :locals =>{:f => f} %>
  
  <p class="buttons">
    <%= submit_tag "Save" %>
    <%= button_to_function "Reset", "$(this).closest('form')[0].reset()" %>
    <%= button_to_function "Cancel", "window.location.replace('#{mixers_path}')" %>
  </p>
<% end %>

app/views/mixers/index.html.erb
<h1>Mixers</h1>

<%= form_tag "", :method => :get, :id => "search_form" do %>
  <%= text_field_tag "search_text", session[:search][:mixer_search_text] %> <%= link_to_function "Search", "$('#search_form').submit()", :class => "search_link" %>
<% end %>

<%= link_to "Add Mixer", new_mixer_path, :class => "create_link" if can?(:create, Mixer) %>

<br class="clear"/><br/>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Active</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
  <% @mixers.each do |mixer| %>  
    <tr class="<%= cycle("light", "dark") %>">
      <td><%= mixer.name %></td>
      <td><%= mixer.brand %></td>
      <td><%= mixer.active ? "Yes" : "No" %></td>
      <td>
        <%= link_to "Edit", edit_mixer_path(mixer), :class => "edit_link" if can?(:update, Mixer) %> &nbsp;&nbsp;
        <%= link_to "Delete", mixer_path(mixer), :class => "delete_link", :method => :delete, :confirm => "Are you sure?" if can?(:delete, Mixer) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @mixers %>

app/views/mixers/new.html.erb
<h1>New Mixer</h1>

<%= render :partial => "shared/error_messages", :locals => {:target => @mixer} %>

<%= form_for @mixer do |f| %>
  <%= render :partial => "form", :locals =>{:f => f} %>
  
  <p class="buttons">
    <%= submit_tag "Save" %>
    <%= button_to_function "Reset", "$('#new_mixer')[0].reset()" %>
    <%= button_to_function "Cancel", "window.location.replace('#{mixers_path}')" %>
  </p>
<% end %>