config/routes.rb
CrownAsia::Application.routes.draw do
  resources :delivery_schedules do
    get 'cancel', :on => :member
    post 'cancel_schedule', :on => :member
    post 'update_item_selection', :on => :collection
  end

  resources :personnels

  resources :positions

  resources :trucks

  resources :generated_certificate_of_qualities do
    get 'search', :on => :collection
    post 'search', :on => :collection
  end

  resources :certificate_of_qualities do
    get 'search', :on => :collection
    post 'search', :on => :collection
  end

  resources :coq_properties

  resources :sales_quotes

  resources :costing_periods

  resources :issued_formula_batches do
    get 'process_batch', :on => :member
    get 'unprocess_batch', :on => :member
  end
  
  resources :issued_formulas do
    post 'update_finished_good', :on => :collection
    post 'update_formula', :on => :collection
    post 'update_item_list', :on => :collection
    post 'show_formula_comment', :on => :collection
    get 'cancel_big_batch', :on => :member
    get 'cancel_small_batch', :on => :member
  end

  resources :formulas do
    post 'update_finished_good', :on => :collection
    post 'update_raw_materials', :on => :collection
  end

  resources :extruders

  resources :mixers

  resources :bags do
    get 'return', :on => :collection
    post 'return', :on => :collection
    post 'update_lot_numbers', :on => :collection
  end
  
  resources :accounts
  
  resources :roles

  resources :finished_good_transactions do
    post 'update_sender', :on => :collection
    post 'update_bags', :on => :collection
    post 'update_issued', :on => :collection
    post 'update_underpack', :on => :collection
  end

  resources :finished_goods do
    get 'transactions', :on => :member
    post 'populate_fields_from_delivery_schedule_items', :on => :member
  end

  resources :supply_transactions do
    post 'update_supplies', :on => :collection
  end

  resources :supplies do
    get 'transactions', :on => :member
  end

  resources :raw_material_transactions do
    post 'update_sender', :on => :collection
    post 'update_issued', :on => :collection
  end

  resources :raw_materials do
    get 'transactions', :on => :member
  end

  resources :raw_material_types

  resources :departments

  resources :unit_of_measures

  resources :customers

  resources :suppliers

  devise_for :users, :path_prefix => 'd'
  
  resources :users
  
  match 'permissions' => 'permissions#index'
  

  root :to => 'home#index'

end

app/models/personnel.rb
class Personnel < ActiveRecord::Base
  validates :first_name, :last_name, :position, :presence => true
  
  belongs_to :position
  
  def name
    "#{self.first_name} #{self.last_name}"
  end
  
  def last_name_first
    "#{self.last_name}, #{self.first_name}"
  end
end

app/controllers/personnels_controller.rb
class PersonnelsController < ApplicationController
  before_filter :authorize_view, :only => [:index]
  before_filter(:only => [:index]) { |c| c.clear_search_session([:last_name, :first_name, :position]) }
  before_filter :authorize_create, :only => [:new, :create]
  before_filter :authorize_update, :only => [:edit, :update]
  before_filter :authorize_delete, :only => [:destroy]
  
  def index
    session[:search][:last_name] = params[:last_name] if !params[:last_name].nil?
    session[:search][:first_name] = params[:first_name] if !params[:first_name].nil?
    session[:search][:position] = params[:position] if !params[:position].nil?
    
    @personnels = Personnel.paginate(:per_page => 20, :page => params[:page])
    @personnels = @personnels.where("last_name LIKE ?", "%#{session[:search][:last_name]}%") unless session[:search][:last_name].blank?
    @personnels = @personnels.where("first_name LIKE ?", "%#{session[:search][:first_name]}%") unless session[:search][:first_name].blank?
    @personnels = @personnels.where("position_id = ?", session[:search][:position]) unless session[:search][:position].blank?
    @personnels = @personnels.order("first_name, last_name")
  end
  
  def new
    @personnel = Personnel.new
  end
  
  def create
    @personnel = Personnel.new(params[:personnel])
    if @personnel.save
      flash[:notice] = "Personnel saved successfully"
      redirect_to personnels_path
    else
      render :action => "new"
    end
  end
  
  def edit
    @personnel = Personnel.find(params[:id])
  end
  
  def update
    @personnel = Personnel.find(params[:id])
    if @personnel.update_attributes(params[:personnel])
      flash[:notice] = "#{@personnel.name} was updated successfully"
      redirect_to personnels_path
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @personnel = Personnel.find(params[:id])
    @personnel.destroy
    flash[:notice] = "#{@personnel.name} was deleted successfully"
    redirect_to personnels_path
  end
  
  protected
  
    def authorize_view
      authorize! :view, Personnel
    end
    
    def authorize_create
      authorize! :create, Personnel
    end
    
    def authorize_update
      authorize! :update, Personnel
    end
    
    def authorize_delete
      authorize! :delete, Personnel
    end
  
end

app/helpers/personnels_helper.rb
module PersonnelsHelper
end

app/views/personnels/_form.html.erb
<fieldset>
  <dl>
    <dd><%= f.label :first_name %></dd>
    <dd><%= f.text_field :first_name %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :last_name %></dd>
    <dd><%= f.text_field :last_name %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :active %></dd>
    <dd><%= f.check_box :active %></dd>
  </dl>
  
  <dl>
    <dd><%= f.label :position_id, "Position" %></dd>
    <dd><%= f.select :position_id, [["", ""]] + Position.where("active = 1").order("name").collect{|p| [p.name, p.id]} %></dd>
  </dl>
</fieldset>

app/views/personnels/edit.html.erb
<h1>Update <%= @personnel.name %></h1>

<%= render :partial => "shared/error_messages", :locals => {:target => @personnel} %>

<%= form_for @personnel do |f| %>
  <%= render :partial => "form", :locals =>{:f => f} %>
  
  <p class="buttons">
    <%= submit_tag "Save" %>
    <%= button_to_function "Reset", "$(this).closest('form')[0].reset()" %>
    <%= button_to_function "Cancel", "window.location.replace('#{personnels_path}')" %>
  </p>
<% end %>

app/views/personnels/index.html.erb
<h1>Personnel s</h1>

<%= form_tag "", :method => :get, :id => "search_form" do %>
  <label>First Name: </label><%= text_field_tag "first_name", session[:search][:first_name] %> 
  <label>Last Name: </label><%= text_field_tag "last_name", session[:search][:last_name] %> 
  <label>Position: </label><%= select_tag "position", options_from_collection_for_select(Position.where("active = 1"), "id", "name", session[:search][:position]), :include_blank => true %> 
  <%= link_to_function "Search", "$('#search_form').submit()", :class => "search_link" %>
<% end %>

<%= link_to "Add Personnel ", new_personnel_path, :class => "create_link" if can?(:create, Personnel ) %>

<br class="clear"/><br/>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
  <% @personnels.each do |personnel| %>
    <tr class="<%= cycle("light", "dark") %>">
      <td><%= personnel.name %></td>
      <td><%= personnel.position.try(:name) %></td>
      <td>
        <%= link_to "Edit", edit_personnel_path(personnel ), :class => "edit_link" if can?(:update, Personnel ) %> &nbsp;&nbsp;
        <%= link_to "Delete", personnel_path(personnel ), :class => "delete_link", :method => :delete, :confirm => "Are you sure?" if can?(:delete, Personnel ) %> <br/>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @personnels %>

app/views/personnels/new.html.erb
<h1>New Personnel</h1>

<%= render :partial => "shared/error_messages", :locals => {:target => @personnel} %>

<%= form_for @personnel do |f| %>
  <%= render :partial => "form", :locals =>{:f => f} %>
  
  <p class="buttons">
    <%= submit_tag "Save" %>
    <%= button_to_function "Reset", "$('#new_personnel')[0].reset()" %>
    <%= button_to_function "Cancel", "window.location.replace('#{personnels_path}')" %>
  </p>
<% end %>